Category.create(name:"hideouts for sale")
Category.create(name:"missed connections")
Category.create(name:"sidekick internship programs")
Category.create(name:"vehicles")
Category.create(name:"awesome gear")
Category.create(name:"miscellaneous")
